name: "Proxmox QDevice"
version: "1.0.0"
description: "QDevice para quorum do cluster Proxmox"
slug: "proxmox_qdevice"
startup: services
boot: auto
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
options:
  listen_address: "0.0.0.0"
schema:
  listen_address: str
